/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5bc180ac-ea60-4fcb-a36a-f3100a36cc3e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rwVu9J1ir",
    "aws_user_pools_web_client_id": "5ve0qvov36i438thqpgituksge",
    "oauth": {}
};


export default awsmobile;
